/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connect;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultTreeCellEditor;

/**
 *
 * @author SHARMA
 */
public class online_test extends javax.swing.JFrame {

    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form online_test
     */
    public online_test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp_add_question = new javax.swing.ButtonGroup();
        btngrp_test = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_add_question_question = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea_add_question = new javax.swing.JTextArea();
        btn_add_question_save = new javax.swing.JButton();
        rbtn_add_question_a = new javax.swing.JRadioButton();
        rbtn_add_question_b = new javax.swing.JRadioButton();
        rbtn_add_question_c = new javax.swing.JRadioButton();
        rbtn_add_question_d = new javax.swing.JRadioButton();
        txt_add_question_b = new javax.swing.JTextField();
        txt_add_question_a = new javax.swing.JTextField();
        txt_add_question_c = new javax.swing.JTextField();
        txt_add_question_d = new javax.swing.JTextField();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        lbl_test_question = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_test_question = new javax.swing.JTextArea();
        btn_test_start_test = new javax.swing.JButton();
        rbtn_test_a = new javax.swing.JRadioButton();
        rbtn_test_b = new javax.swing.JRadioButton();
        rbtn_test_c = new javax.swing.JRadioButton();
        rbtn_test_d = new javax.swing.JRadioButton();
        txt_test_b = new javax.swing.JTextField();
        txt_test_d = new javax.swing.JTextField();
        txt_test_c = new javax.swing.JTextField();
        txt_test_a = new javax.swing.JTextField();
        btn_test_next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_test_score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(172, 208, 154));

        lbl_add_question_question.setText("Question:");

        txtarea_add_question.setColumns(20);
        txtarea_add_question.setRows(5);
        jScrollPane1.setViewportView(txtarea_add_question);

        btn_add_question_save.setText("Save");
        btn_add_question_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_question_saveActionPerformed(evt);
            }
        });

        btngrp_add_question.add(rbtn_add_question_a);
        rbtn_add_question_a.setText("A");

        btngrp_add_question.add(rbtn_add_question_b);
        rbtn_add_question_b.setText("B");

        btngrp_add_question.add(rbtn_add_question_c);
        rbtn_add_question_c.setText("C");

        btngrp_add_question.add(rbtn_add_question_d);
        rbtn_add_question_d.setText("D");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbl_add_question_question)
                .addGap(43, 43, 43)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(rbtn_add_question_c)
                                .addGap(18, 18, 18)
                                .addComponent(txt_add_question_c))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(rbtn_add_question_a)
                                .addGap(18, 18, 18)
                                .addComponent(txt_add_question_a, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtn_add_question_b)
                            .addComponent(rbtn_add_question_d))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_add_question_d, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txt_add_question_b)))
                    .addComponent(jScrollPane1))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_add_question_save)
                .addGap(200, 200, 200))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_add_question_question)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_add_question_a)
                    .addComponent(txt_add_question_a, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtn_add_question_b)
                    .addComponent(txt_add_question_b, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_add_question_c)
                    .addComponent(txt_add_question_c, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtn_add_question_d)
                    .addComponent(txt_add_question_d, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btn_add_question_save)
                .addGap(65, 65, 65))
        );
        jDesktopPane1.setLayer(lbl_add_question_question, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btn_add_question_save, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rbtn_add_question_a, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rbtn_add_question_b, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rbtn_add_question_c, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rbtn_add_question_d, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txt_add_question_b, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txt_add_question_a, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txt_add_question_c, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txt_add_question_d, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Add Question", jDesktopPane1);

        jDesktopPane2.setBackground(new java.awt.Color(172, 208, 154));
        jDesktopPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDesktopPane2MouseEntered(evt);
            }
        });

        lbl_test_question.setText("Question:");

        txt_test_question.setColumns(20);
        txt_test_question.setRows(5);
        jScrollPane2.setViewportView(txt_test_question);

        btn_test_start_test.setText("Start Test");
        btn_test_start_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_test_start_testActionPerformed(evt);
            }
        });

        btngrp_test.add(rbtn_test_a);
        rbtn_test_a.setText("A");

        btngrp_test.add(rbtn_test_b);
        rbtn_test_b.setText("B");

        btngrp_test.add(rbtn_test_c);
        rbtn_test_c.setText("C");

        btngrp_test.add(rbtn_test_d);
        rbtn_test_d.setText("D");

        btn_test_next.setText("Next");
        btn_test_next.setEnabled(false);
        btn_test_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_test_nextActionPerformed(evt);
            }
        });

        jLabel1.setText("Total Score: ");

        lbl_test_score.setText("jLabel2");

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_test_question)
                .addGap(61, 61, 61)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(btn_test_start_test)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_test_score)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                        .addComponent(rbtn_test_a)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_test_a, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                        .addComponent(rbtn_test_c)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_test_c, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                        .addComponent(rbtn_test_b)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_test_b, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(rbtn_test_d)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_test_d, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addComponent(btn_test_next)
                                .addGap(155, 155, 155)))
                        .addGap(46, 46, 46))))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_test_start_test)
                    .addComponent(jLabel1)
                    .addComponent(lbl_test_score))
                .addGap(12, 12, 12)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_test_question))
                .addGap(48, 48, 48)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_test_b)
                    .addComponent(txt_test_b, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_test_a, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtn_test_a))
                .addGap(41, 41, 41)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_test_d, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_test_c, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtn_test_c)
                    .addComponent(rbtn_test_d))
                .addGap(38, 38, 38)
                .addComponent(btn_test_next)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jDesktopPane2.setLayer(lbl_test_question, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btn_test_start_test, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(rbtn_test_a, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(rbtn_test_b, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(rbtn_test_c, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(rbtn_test_d, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(txt_test_b, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(txt_test_d, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(txt_test_c, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(txt_test_a, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btn_test_next, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(lbl_test_score, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Test", jDesktopPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btn_add_question_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_question_saveActionPerformed
        // TODO add your handling code here:
        String sql;
        String question = txtarea_add_question.getText();
        if(question.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Question cannot be Empty");
            return;
        }
        String opta = txt_add_question_a.getText();
        if(opta.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Option A cannot be Empty");
            return;
        }
        String optb = txt_add_question_b.getText();
        if(optb.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Option B cannot be Empty");
            return;
        }
        String optc = txt_add_question_c.getText();
        if(optc.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Option C cannot be Empty");
            return;
        }
        String optd = txt_add_question_d.getText();
        if(optd.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Option D cannot be Empty");
            return;
        }
        String answer="";
        if(rbtn_add_question_a.isSelected())
        {
            answer="A";
        }
        if(rbtn_add_question_b.isSelected())
        {
            answer="B";
        }
        if(rbtn_add_question_c.isSelected())
        {
            answer="C";
        }
        if(rbtn_add_question_d.isSelected())
        {
            answer="D";
        }
        if(answer.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please selct An Answer");
            return;
        }
        sql = "Insert into tablequestion (question,option_a,option_b,option_c,option_d,answer) values ('" +  question + "','" + opta +"','" + optb + "','" + optc + "','" + optd +"','"+answer+ "')";
         try
      {
           conn = Connect.ConnectDB();
           pst = conn.prepareStatement(sql);
           pst.executeUpdate();
        
           txtarea_add_question.setText("");
           txt_add_question_a.setText("");
           txt_add_question_b.setText("");
           txt_add_question_c.setText("");
           txt_add_question_d.setText("");
           conn.close();
      }
     catch(SQLException | HeadlessException e)
     {
          JOptionPane.showMessageDialog(null, e);          
     }
           
    }//GEN-LAST:event_btn_add_question_saveActionPerformed
    static int question_no=1;
    static String correct_answer = ""; 
    static int total_score = 0;
    private void btn_test_start_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_test_start_testActionPerformed

        question_no=1;
        lbl_test_question.setText("Question No: " + question_no);
        String sql = "SELECT * FROM tablequestion WHERE rowid='" + question_no + "'";
        try
        {
            conn = Connect.ConnectDB();
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next())
            {
                txt_test_question.setText(rs.getString("question"));
                txt_test_a.setText(rs.getString("option_a"));
                txt_test_b.setText(rs.getString("option_b"));
                txt_test_c.setText(rs.getString("option_c"));
                txt_test_d.setText(rs.getString("option_d"));
                correct_answer = rs.getString("answer");
            }
            btn_test_next.setEnabled(true);
            btn_test_start_test.setEnabled(false);
            conn.close();
        }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);          
        }
    }//GEN-LAST:event_btn_test_start_testActionPerformed

    private void jDesktopPane2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane2MouseEntered
        lbl_test_score.setText(Integer.toString(total_score));
 
    }//GEN-LAST:event_jDesktopPane2MouseEntered

    private void btn_test_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_test_nextActionPerformed
        String answer="";
        if(rbtn_test_a.isSelected())
        {
            answer="A";
        }
        if(rbtn_test_b.isSelected())
        {
            answer="B";
        }
        if(rbtn_test_c.isSelected())
        {
            answer="C";
        }
        if(rbtn_test_d.isSelected())
        {
            answer="D";
        }
        if(answer.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please selct An Answer");
            return;
        }
        
        if(correct_answer.equals(answer))
        {
            JOptionPane.showMessageDialog(null, "Right Answer");
            total_score += 10;
            lbl_test_score.setText(Integer.toString(total_score));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Wrong Answer");
            total_score -= 5;
            lbl_test_score.setText(Integer.toString(total_score));
        }
        
        rbtn_test_a.setSelected(false);
        rbtn_test_b.setSelected(false);
        rbtn_test_c.setSelected(false);
        rbtn_test_d.setSelected(false);
        
        if(question_no >= 10)
        {
            JOptionPane.showMessageDialog(null, "Test Over : 10 Questions Complete");
            btn_test_next.setEnabled(false);
            rbtn_test_a.setSelected(false);
            rbtn_test_b.setSelected(false);
            rbtn_test_c.setSelected(false);
            rbtn_test_d.setSelected(false);
            btn_test_start_test.setEnabled(true);
            txt_test_question.setText("");
            txt_test_a.setText("");
            txt_test_b.setText("");
            txt_test_c.setText("");
            txt_test_d.setText("");
            total_score = 0;
            lbl_test_score.setText(Integer.toString(total_score));
            
            question_no=1;
            correct_answer="";
            return;
        }
        
        // get next question
        question_no++;
        lbl_test_question.setText("Question No: " + question_no);
        String sql = "SELECT * FROM tablequestion WHERE rowid='" + question_no + "'";
        try
        {
            conn = Connect.ConnectDB();
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next())
            {
                txt_test_question.setText(rs.getString("question"));
                txt_test_a.setText(rs.getString("option_a"));
                txt_test_b.setText(rs.getString("option_b"));
                txt_test_c.setText(rs.getString("option_c"));
                txt_test_d.setText(rs.getString("option_d"));
                correct_answer = rs.getString("answer");
             }

            conn.close();
        }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);          
        }
    }//GEN-LAST:event_btn_test_nextActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(online_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(online_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(online_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(online_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new online_test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_question_save;
    private javax.swing.JButton btn_test_next;
    private javax.swing.JButton btn_test_start_test;
    private javax.swing.ButtonGroup btngrp_add_question;
    private javax.swing.ButtonGroup btngrp_test;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_add_question_question;
    private javax.swing.JLabel lbl_test_question;
    private javax.swing.JLabel lbl_test_score;
    private javax.swing.JRadioButton rbtn_add_question_a;
    private javax.swing.JRadioButton rbtn_add_question_b;
    private javax.swing.JRadioButton rbtn_add_question_c;
    private javax.swing.JRadioButton rbtn_add_question_d;
    private javax.swing.JRadioButton rbtn_test_a;
    private javax.swing.JRadioButton rbtn_test_b;
    private javax.swing.JRadioButton rbtn_test_c;
    private javax.swing.JRadioButton rbtn_test_d;
    private javax.swing.JTextField txt_add_question_a;
    private javax.swing.JTextField txt_add_question_b;
    private javax.swing.JTextField txt_add_question_c;
    private javax.swing.JTextField txt_add_question_d;
    private javax.swing.JTextField txt_test_a;
    private javax.swing.JTextField txt_test_b;
    private javax.swing.JTextField txt_test_c;
    private javax.swing.JTextField txt_test_d;
    private javax.swing.JTextArea txt_test_question;
    private javax.swing.JTextArea txtarea_add_question;
    // End of variables declaration//GEN-END:variables
}
