/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connect;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultTreeCellEditor;

/**
 *
 * @author SHARMA
 */
public class online_test extends javax.swing.JFrame {

    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form online_test
     */
    public online_test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_add_question_question = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea_add_question = new javax.swing.JTextArea();
        btn_add_question_next = new javax.swing.JButton();
        rbtn_add_question_a = new javax.swing.JRadioButton();
        rbtn_add_question_b = new javax.swing.JRadioButton();
        rbtn_add_question_c = new javax.swing.JRadioButton();
        rbtn_add_question_d = new javax.swing.JRadioButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        lbl_test_question = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtarea_test = new javax.swing.JTextArea();
        btn_test_next = new javax.swing.JButton();
        rbtn_test_a = new javax.swing.JRadioButton();
        rbtn_test_b = new javax.swing.JRadioButton();
        rbtn_test_c = new javax.swing.JRadioButton();
        rbtn_test_d = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseEntered(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));

        lbl_add_question_question.setText("Question:");

        txtarea_add_question.setColumns(20);
        txtarea_add_question.setRows(5);
        jScrollPane1.setViewportView(txtarea_add_question);

        btn_add_question_next.setText("Next");
        btn_add_question_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_question_nextActionPerformed(evt);
            }
        });

        rbtn_add_question_a.setText("A");

        rbtn_add_question_b.setText("B");

        rbtn_add_question_c.setText("C");

        rbtn_add_question_d.setText("D");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lbl_add_question_question)
                        .addGap(39, 39, 39)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtn_add_question_c)
                            .addComponent(rbtn_add_question_a)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtn_add_question_b)
                            .addComponent(rbtn_add_question_d)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btn_add_question_next)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_add_question_question)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_add_question_a)
                    .addComponent(rbtn_add_question_b))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_add_question_c)
                    .addComponent(rbtn_add_question_d))
                .addGap(18, 18, 18)
                .addComponent(btn_add_question_next)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(lbl_add_question_question, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btn_add_question_next, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rbtn_add_question_a, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rbtn_add_question_b, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rbtn_add_question_c, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rbtn_add_question_d, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Add Question", jDesktopPane1);

        jDesktopPane2.setBackground(new java.awt.Color(240, 240, 240));

        lbl_test_question.setText("Question:");

        txtarea_test.setColumns(20);
        txtarea_test.setRows(5);
        jScrollPane2.setViewportView(txtarea_test);

        btn_test_next.setText("Next");

        rbtn_test_a.setText("A");

        rbtn_test_b.setText("B");

        rbtn_test_c.setText("C");

        rbtn_test_d.setText("D");

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lbl_test_question)
                        .addGap(37, 37, 37)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn_test_a)
                                    .addComponent(rbtn_test_c))
                                .addGap(64, 64, 64)
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn_test_b)
                                    .addComponent(rbtn_test_d)))))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btn_test_next)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_test_question))
                .addGap(30, 30, 30)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_test_a)
                    .addComponent(rbtn_test_b))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_test_c)
                    .addComponent(rbtn_test_d))
                .addGap(18, 18, 18)
                .addComponent(btn_test_next)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jDesktopPane2.setLayer(lbl_test_question, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btn_test_next, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(rbtn_test_a, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(rbtn_test_b, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(rbtn_test_c, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(rbtn_test_d, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Test", jDesktopPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void btn_add_question_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_question_nextActionPerformed
        // TODO add your handling code here:
        String sql;
        String question = txtarea_add_question.getText();
        
        sql = "Insert into tablequestion (question) values ('" +  question + "')";
         try
      {
           conn = Connect.ConnectDB();
           pst = conn.prepareStatement(sql);
           pst.executeUpdate();
        
           JOptionPane.showMessageDialog(null, "saved");
           txtarea_add_question.setText("");
           
           conn.close();
           
           
      }
     catch(SQLException | HeadlessException e)
     {
          JOptionPane.showMessageDialog(null, e);          
     }
        
    }//GEN-LAST:event_btn_add_question_nextActionPerformed

    private void jTabbedPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseEntered
        // TODO add your handling code here:
        
         String sql;
        String question=null;
      sql = "SELECT * FROM tablequestion where question ='"+question+"'";
            
      try
      {
          List result = new ArrayList();
        conn = Connect.ConnectDB();
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        if(rs.next()){
            do
            {
          // Object row[]={ rs.getString("question")};
           

                String s = rs.getString("question");
                txtarea_test.append(s);
          // txtarea_test.setValue
       
       // DefaultTableModel model = (DefaultTableModel) txtarea_test.getModel();
        // model.addRow(row);
                
            }while(rs.next());
           }
        conn.close();
      }
     catch(SQLException | HeadlessException e)
     {
          JOptionPane.showMessageDialog(null, e);          
     }
    }//GEN-LAST:event_jTabbedPane1MouseEntered

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(online_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(online_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(online_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(online_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new online_test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_question_next;
    private javax.swing.JButton btn_test_next;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_add_question_question;
    private javax.swing.JLabel lbl_test_question;
    private javax.swing.JRadioButton rbtn_add_question_a;
    private javax.swing.JRadioButton rbtn_add_question_b;
    private javax.swing.JRadioButton rbtn_add_question_c;
    private javax.swing.JRadioButton rbtn_add_question_d;
    private javax.swing.JRadioButton rbtn_test_a;
    private javax.swing.JRadioButton rbtn_test_b;
    private javax.swing.JRadioButton rbtn_test_c;
    private javax.swing.JRadioButton rbtn_test_d;
    private javax.swing.JTextArea txtarea_add_question;
    private javax.swing.JTextArea txtarea_test;
    // End of variables declaration//GEN-END:variables
}
